### ISSUE TITLE
Не работает админка

### ISSUE THREAD

**Issue by CatCoderr** [xtrafrancyz/golish#1]
При переходе на страницу **http://{host}/@admin/** (с дефолтным конфигом) выскакивает следующее сообщение: `404 Page not found`
Логи:
```
2020/04/02 19:00:02 Loaded 0 links
2020/04/02 19:00:02 Starting server on http://0.0.0.0:34532
2020/04/02 19:01:14 {admin}/index.html
```

Где запускался:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch
```

**Comment by xtrafrancyz** [comment]
В скомпилированном виде нужно чтобы одно из следующего выполнялось:
- В рабочей папке должна быть папка `admin` с файлами админки;
- Папка `admin` должна быть добавлена в бинарник через [rice](https://github.com/GeertJohan/go.rice).

Пример сборки бинарника есть в [build.bat](https://github.com/xtrafrancyz/golish/blob/eb7f580180e184bf85550bf2e138d2e5f1afd9e5/scripts/build.bat#L7).

**Comment by CatCoderr** [comment]
Использовал первый вариант - та же ошибка. Вот как выглядит папка с бинарником:
![image](https://user-images.githubusercontent.com/21067004/78300005-74220f00-753f-11ea-9667-210459ad81b8.png)

**Comment by xtrafrancyz** [comment]
Может зависимости обновились и стали несовместимыми. Обновил и добавил в go.mod https://github.com/xtrafrancyz/golish/commit/e29742c43e0d1c704844bdd459b024d396d6c92f, может сейчас будет работать. В релизах новый билд есть, или самостоятельно собрать.

UPD: Проверил у себя на сервере Debian 8, после `go build` и запуска из той же директории все работает.

**Comment by CatCoderr** [comment]
Оказывается проблема была в другом. У меня переменная GOPATH была не установлена на нужную директорию. Вопрос закрыт.
